CREATE TABLE custom_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collective_code VARCHAR(255) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    title VARCHAR(80) NOT NULL,
    description VARCHAR(240) NOT NULL,
    metric VARCHAR(32) NOT NULL,
    target INTEGER NOT NULL,
    task_category VARCHAR(32),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT chk_custom_achievement_target CHECK (target > 0)
);

CREATE INDEX idx_custom_achievements_collective_code
    ON custom_achievements (collective_code);
