create table friendships (
    id bigint generated by default as identity primary key,
    member_id bigint not null references members (id) on delete cascade,
    friend_id bigint not null references members (id) on delete cascade,
    constraint uq_friendships_member_friend unique (member_id, friend_id),
    constraint ck_friendships_not_self check (member_id <> friend_id)
);

create index idx_friendships_friend_id on friendships (friend_id);
