create table task_swap_requests (
    id bigint generated by default as identity primary key,
    from_user varchar(255) not null,
    to_user varchar(255) not null,
    task_id bigint not null,
    status varchar(32) not null,
    expires_at timestamp(6) with time zone not null,
    constraint fk_task_swap_requests_task
        foreign key (task_id) references tasks (id) on delete cascade
);

create index idx_task_swap_requests_to_user on task_swap_requests (to_user);
create index idx_task_swap_requests_task_status on task_swap_requests (task_id, status);
