create table house_checkins (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    week_start date not null,
    created_at timestamp(6) not null,
    constraint uq_house_checkins_collective_week unique (collective_code, week_start)
);

create table checkin_responses (
    id bigint generated by default as identity primary key,
    checkin_id bigint not null,
    member_name varchar(255) not null,
    mood integer not null,
    issue varchar(1000) not null,
    improvement varchar(1000) not null,
    anonymous boolean not null,
    created_at timestamp(6) not null,
    constraint fk_checkin_responses_checkin foreign key (checkin_id) references house_checkins (id) on delete cascade,
    constraint uq_checkin_responses_member unique (checkin_id, member_name),
    constraint ck_checkin_responses_mood check (mood between 1 and 5)
);
