create table house_rules (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    version integer not null,
    content text not null,
    updated_by varchar(255) not null,
    created_at timestamp(6) not null,
    constraint uq_house_rules_collective_version unique (collective_code, version)
);

create table house_rule_ack (
    id bigint generated by default as identity primary key,
    rule_id bigint not null,
    member_name varchar(255) not null,
    acknowledged_at timestamp(6) not null,
    constraint fk_house_rule_ack_rule foreign key (rule_id) references house_rules (id) on delete cascade,
    constraint uq_house_rule_ack_member unique (rule_id, member_name)
);
