create table guest_notices (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    created_by varchar(255) not null,
    guest_name varchar(255) not null,
    notice_date date not null,
    start_time time not null,
    end_time time not null,
    overnight boolean not null,
    created_at timestamp(6) not null
);

create index idx_guest_notices_collective_date on guest_notices (collective_code, notice_date);

create table collective_quiet_hours (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    enabled boolean not null,
    start_time time not null,
    end_time time not null,
    constraint uq_collective_quiet_hours_code unique (collective_code)
);
