create table maintenance_ticket (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    title varchar(255) not null,
    description varchar(1500) not null,
    priority varchar(32) not null,
    status varchar(32) not null,
    assignee varchar(255),
    due_date date,
    cost_estimate integer,
    created_by varchar(255) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create index idx_maintenance_ticket_collective on maintenance_ticket (collective_code);

create table maintenance_ticket_status_history (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    status varchar(32) not null,
    changed_by varchar(255) not null,
    changed_at timestamp(6) not null,
    constraint fk_maintenance_history_ticket foreign key (ticket_id) references maintenance_ticket (id) on delete cascade
);
