create table kudos (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    sender varchar(255) not null,
    receiver varchar(255) not null,
    task_id bigint,
    context varchar(500) not null,
    created_at timestamp(6) not null,
    constraint fk_kudos_task foreign key (task_id) references tasks (id) on delete set null
);

create index idx_kudos_collective_created on kudos (collective_code, created_at);
create index idx_kudos_sender_created on kudos (sender, created_at);
