-- Archive of stat-relevant task facts, written before a task row is deleted
-- (5 days after its due date). Keeps XP (lifetime/yearly/monthly), achievements
-- and fairness history intact while live task rows stay pruned. Member.xp remains
-- the authoritative lifetime XP and is never derived from this table.
CREATE TABLE task_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collective_code VARCHAR(255),
    assignee VARCHAR(255) NOT NULL,
    completed_by VARCHAR(255),
    due_date DATE NOT NULL,
    category VARCHAR(64) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP,
    xp INTEGER NOT NULL DEFAULT 0,
    penalty_xp INTEGER NOT NULL DEFAULT 0,
    recurrence_rule VARCHAR(128),
    original_task_id BIGINT
);

CREATE INDEX idx_task_history_collective_code ON task_history (collective_code);
