create table event_attendance (
    id bigint generated by default as identity primary key,
    event_id bigint not null,
    member_name varchar(255) not null,
    status varchar(16) not null,
    constraint fk_event_attendance_event foreign key (event_id) references events (id) on delete cascade,
    constraint uq_event_attendance unique (event_id, member_name)
);

create index idx_event_attendance_event on event_attendance (event_id);
