-- Per-category monthly spending caps a household sets for itself. One row per category per
-- collective; the cap recurs every month, so there is no month/year column here — actual spend
-- for "this month" is derived from `expenses` at read time (see EconomyOperations.getBudgets).
create table budgets (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    category varchar(255) not null
        check (category in ('Groceries', 'Bills', 'Cleaning', 'Entertainment', 'Food', 'Other')),
    monthly_limit integer not null check (monthly_limit >= 0),
    unique (collective_code, category)
);

create index idx_budgets_collective_code on budgets (collective_code);

alter table budgets enable row level security;
