-- Open discussion topics a household member proposes for the running weekly house-meeting
-- agenda. "Posting to chat" (introducing a topic into the household thread for comments) reuses
-- the existing POST /api/chat/messages send path from the frontend -- no chat-side FK is stored here.
create table meeting_topics (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    title varchar(300) not null,
    created_by varchar(255) not null,
    created_at timestamp not null default now(),
    resolved boolean not null default false
);

create index idx_meeting_topics_collective on meeting_topics (collective_code, resolved);

alter table meeting_topics enable row level security;
