-- Tracks Google Cloud Vision API calls per calendar month so the backend can stop calling it once
-- the free-tier limit is reached, instead of relying on Google Cloud's imprecise quota enforcement.
create table vision_api_usage (
    id bigint generated by default as identity primary key,
    period varchar(7) not null unique, -- e.g. "2026-08"
    call_count integer not null default 0
);

alter table vision_api_usage enable row level security;
