-- Chat wallpapers, shared by everyone in a thread. Previously each device kept its own picture in
-- localStorage, so "changing the background" only ever changed it for the person who did it.
--
-- One row per thread. thread_key is canonical so both sides of a direct message resolve to the same
-- row regardless of who set the picture: 'household' for the collective-wide thread, and
-- 'dm:<lower>|<higher>' (the two member names sorted) for a pair. Stored as text because two
-- 255-char names plus the prefix can exceed any comfortable varchar bound.
--
-- image_data is base64, matching how chat_messages already stores image attachments -- the same
-- ImageSafetyService validates, downscales and moderates it before it lands here.
create table chat_backgrounds (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    thread_key text not null,
    image_data text not null,
    image_mime_type varchar(64) not null,
    set_by varchar(255) not null,
    updated_at timestamptz not null default now(),
    constraint uq_chat_backgrounds_thread unique (collective_code, thread_key)
);

alter table chat_backgrounds enable row level security;
